import '../models/psychometric_question.dart';

const mockQuestions = <PsychometricQuestion>[
  // ─── Personality (5) ───
  PsychometricQuestion(
    id: 'p1',
    text: 'How do you feel after spending time with a large group of people?',
    category: QuestionCategory.personality,
    type: QuestionType.singleChoice,
    emoji: '\u{1F465}',
    options: [
      'Energized and excited',
      'Neutral — depends on the group',
      'A bit drained, need alone time',
      'Exhausted — I need to recharge',
    ],
  ),
  PsychometricQuestion(
    id: 'p2',
    text: 'When facing a new challenge, what is your first instinct?',
    category: QuestionCategory.personality,
    type: QuestionType.singleChoice,
    emoji: '\u{1F9E0}',
    options: [
      'Jump right in and figure it out',
      'Research and plan before starting',
      'Ask someone experienced for advice',
      'Wait and observe others first',
    ],
  ),
  PsychometricQuestion(
    id: 'p3',
    text: 'Which of these describe you? Select all that apply.',
    category: QuestionCategory.personality,
    type: QuestionType.multiChoice,
    emoji: '\u{2728}',
    options: [
      'Creative thinker',
      'Detail-oriented',
      'Empathetic listener',
      'Natural leader',
      'Analytical problem-solver',
      'Spontaneous adventurer',
    ],
  ),
  PsychometricQuestion(
    id: 'p4',
    text: 'How comfortable are you sharing your feelings with others?',
    category: QuestionCategory.personality,
    type: QuestionType.slider,
    emoji: '\u{1F4AC}',
    sliderMin: 1,
    sliderMax: 5,
    sliderMinLabel: 'Very private',
    sliderMaxLabel: 'Very open',
  ),
  PsychometricQuestion(
    id: 'p5',
    text: 'In a few words, what quality do you value most in a friend?',
    category: QuestionCategory.personality,
    type: QuestionType.freeText,
    emoji: '\u{1F91D}',
  ),

  // ─── Work Habits (5) ───
  PsychometricQuestion(
    id: 'w1',
    text: 'What does your ideal work schedule look like?',
    category: QuestionCategory.workHabit,
    type: QuestionType.singleChoice,
    emoji: '\u{1F4C5}',
    options: [
      'Strict 9-to-5 routine',
      'Flexible hours with some structure',
      'Completely flexible — I work when inspired',
      'Night owl — I do my best work late',
    ],
  ),
  PsychometricQuestion(
    id: 'w2',
    text: 'How do you prefer to collaborate on projects?',
    category: QuestionCategory.workHabit,
    type: QuestionType.singleChoice,
    emoji: '\u{1F465}',
    options: [
      'Solo — I work best alone',
      'Small team of 2-3 people',
      'Larger group with clear roles',
      'Pair work — one partner is ideal',
    ],
  ),
  PsychometricQuestion(
    id: 'w3',
    text: 'Which work habits do you struggle with? Select all that apply.',
    category: QuestionCategory.workHabit,
    type: QuestionType.multiChoice,
    emoji: '\u{1F62C}',
    options: [
      'Procrastination',
      'Overworking / burnout',
      'Difficulty focusing',
      'Perfectionism',
      'Time management',
      'Saying no to requests',
    ],
  ),
  PsychometricQuestion(
    id: 'w4',
    text: 'How would you rate your work-life balance right now?',
    category: QuestionCategory.workHabit,
    type: QuestionType.slider,
    emoji: '\u{2696}\u{FE0F}',
    sliderMin: 1,
    sliderMax: 5,
    sliderMinLabel: 'All work',
    sliderMaxLabel: 'Well balanced',
  ),
  PsychometricQuestion(
    id: 'w5',
    text: 'What motivates you the most at work or school?',
    category: QuestionCategory.workHabit,
    type: QuestionType.freeText,
    emoji: '\u{1F680}',
  ),

  // ─── Stress Triggers (5) ───
  PsychometricQuestion(
    id: 's1',
    text: 'What tends to stress you out the most?',
    category: QuestionCategory.stressTrigger,
    type: QuestionType.singleChoice,
    emoji: '\u{1F4A5}',
    options: [
      'Tight deadlines and time pressure',
      'Social conflicts or misunderstandings',
      'Uncertainty about the future',
      'Feeling overwhelmed by too many tasks',
    ],
  ),
  PsychometricQuestion(
    id: 's2',
    text: 'When you feel stressed, what do you usually do first?',
    category: QuestionCategory.stressTrigger,
    type: QuestionType.singleChoice,
    emoji: '\u{1F6E1}\u{FE0F}',
    options: [
      'Talk to someone I trust',
      'Take a break or go for a walk',
      'Push through and keep working',
      'Distract myself with entertainment',
    ],
  ),
  PsychometricQuestion(
    id: 's3',
    text: 'Which of these have you experienced recently? Select all that apply.',
    category: QuestionCategory.stressTrigger,
    type: QuestionType.multiChoice,
    emoji: '\u{1F614}',
    options: [
      'Trouble sleeping',
      'Loss of motivation',
      'Feeling anxious or on edge',
      'Difficulty concentrating',
      'Physical tension (headaches, etc.)',
      'Withdrawing from friends/family',
    ],
  ),
  PsychometricQuestion(
    id: 's4',
    text: 'How well do you feel you manage stress overall?',
    category: QuestionCategory.stressTrigger,
    type: QuestionType.slider,
    emoji: '\u{1F4AA}',
    sliderMin: 1,
    sliderMax: 5,
    sliderMinLabel: 'Struggling',
    sliderMaxLabel: 'Managing well',
  ),
  PsychometricQuestion(
    id: 's5',
    text: 'What is one thing that always helps you feel better?',
    category: QuestionCategory.stressTrigger,
    type: QuestionType.freeText,
    emoji: '\u{2600}\u{FE0F}',
  ),
];
